### ISSUE TITLE
Problem running au run --watch on OS X

### ISSUE THREAD

**Issue by col-panic** [rgwch/webelexis-es#1]
Starting au run --watch leaves me with the following error on OS X.

```
marco@Marcos-MacBook-Pro ~/g/webelexis-es> au run --watch
/Users/marco/git/webelexis-es/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.0
    at module.exports (/Users/marco/git/webelexis-es/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/marco/git/webelexis-es/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/marco/git/webelexis-es/node_modules/gulp-sass/index.js:187:21)
```

**Comment by col-panic** [comment]
Konnte Problem durch doku in https://github.com/rgwch/webelexis/blob/master/client/vorbereitung.md lösen!
